"""
List of countries with their ISO codes and names in English and German.
Based on ISO 3166-1 standard.
"""

COUNTRIES = {
    'AF': {'en': 'Afghanistan', 'de': 'Afghanistan'},
    'AL': {'en': 'Albania', 'de': 'Albanien'},
    'DZ': {'en': 'Algeria', 'de': 'Algerien'},
    'AD': {'en': 'Andorra', 'de': 'Andorra'},
    'AO': {'en': 'Angola', 'de': 'Angola'},
    'AG': {'en': 'Antigua and Barbuda', 'de': 'Antigua und Barbuda'},
    'AR': {'en': 'Argentina', 'de': 'Argentinien'},
    'AM': {'en': 'Armenia', 'de': 'Armenien'},
    'AU': {'en': 'Australia', 'de': 'Australien'},
    'AT': {'en': 'Austria', 'de': 'Österreich'},
    'AZ': {'en': 'Azerbaijan', 'de': 'Aserbaidschan'},
    'BS': {'en': 'Bahamas', 'de': 'Bahamas'},
    'BH': {'en': 'Bahrain', 'de': 'Bahrain'},
    'BD': {'en': 'Bangladesh', 'de': 'Bangladesch'},
    'BB': {'en': 'Barbados', 'de': 'Barbados'},
    'BY': {'en': 'Belarus', 'de': 'Weißrussland'},
    'BE': {'en': 'Belgium', 'de': 'Belgien'},
    'BZ': {'en': 'Belize', 'de': 'Belize'},
    'BJ': {'en': 'Benin', 'de': 'Benin'},
    'BT': {'en': 'Bhutan', 'de': 'Bhutan'},
    'BO': {'en': 'Bolivia', 'de': 'Bolivien'},
    'BA': {'en': 'Bosnia and Herzegovina', 'de': 'Bosnien und Herzegowina'},
    'BW': {'en': 'Botswana', 'de': 'Botswana'},
    'BR': {'en': 'Brazil', 'de': 'Brasilien'},
    'BN': {'en': 'Brunei', 'de': 'Brunei'},
    'BG': {'en': 'Bulgaria', 'de': 'Bulgarien'},
    'BF': {'en': 'Burkina Faso', 'de': 'Burkina Faso'},
    'BI': {'en': 'Burundi', 'de': 'Burundi'},
    'KH': {'en': 'Cambodia', 'de': 'Kambodscha'},
    'CM': {'en': 'Cameroon', 'de': 'Kamerun'},
    'CA': {'en': 'Canada', 'de': 'Kanada'},
    'CV': {'en': 'Cape Verde', 'de': 'Kap Verde'},
    'CF': {'en': 'Central African Republic', 'de': 'Zentralafrikanische Republik'},
    'TD': {'en': 'Chad', 'de': 'Tschad'},
    'CL': {'en': 'Chile', 'de': 'Chile'},
    'CN': {'en': 'China', 'de': 'China'},
    'CO': {'en': 'Colombia', 'de': 'Kolumbien'},
    'KM': {'en': 'Comoros', 'de': 'Komoren'},
    'CG': {'en': 'Congo', 'de': 'Kongo'},
    'CR': {'en': 'Costa Rica', 'de': 'Costa Rica'},
    'HR': {'en': 'Croatia', 'de': 'Kroatien'},
    'CU': {'en': 'Cuba', 'de': 'Kuba'},
    'CY': {'en': 'Cyprus', 'de': 'Zypern'},
    'CZ': {'en': 'Czech Republic', 'de': 'Tschechische Republik'},
    'DK': {'en': 'Denmark', 'de': 'Dänemark'},
    'DJ': {'en': 'Djibouti', 'de': 'Dschibuti'},
    'DM': {'en': 'Dominica', 'de': 'Dominica'},
    'DO': {'en': 'Dominican Republic', 'de': 'Dominikanische Republik'},
    'EC': {'en': 'Ecuador', 'de': 'Ecuador'},
    'EG': {'en': 'Egypt', 'de': 'Ägypten'},
    'SV': {'en': 'El Salvador', 'de': 'El Salvador'},
    'GQ': {'en': 'Equatorial Guinea', 'de': 'Äquatorialguinea'},
    'ER': {'en': 'Eritrea', 'de': 'Eritrea'},
    'EE': {'en': 'Estonia', 'de': 'Estland'},
    'ET': {'en': 'Ethiopia', 'de': 'Äthiopien'},
    'FJ': {'en': 'Fiji', 'de': 'Fidschi'},
    'FI': {'en': 'Finland', 'de': 'Finnland'},
    'FR': {'en': 'France', 'de': 'Frankreich'},
    'GA': {'en': 'Gabon', 'de': 'Gabun'},
    'GM': {'en': 'Gambia', 'de': 'Gambia'},
    'GE': {'en': 'Georgia', 'de': 'Georgien'},
    'DE': {'en': 'Germany', 'de': 'Deutschland'},
    'GH': {'en': 'Ghana', 'de': 'Ghana'},
    'GR': {'en': 'Greece', 'de': 'Griechenland'},
    'GD': {'en': 'Grenada', 'de': 'Grenada'},
    'GT': {'en': 'Guatemala', 'de': 'Guatemala'},
    'GN': {'en': 'Guinea', 'de': 'Guinea'},
    'GW': {'en': 'Guinea-Bissau', 'de': 'Guinea-Bissau'},
    'GY': {'en': 'Guyana', 'de': 'Guyana'},
    'HT': {'en': 'Haiti', 'de': 'Haiti'},
    'HN': {'en': 'Honduras', 'de': 'Honduras'},
    'HU': {'en': 'Hungary', 'de': 'Ungarn'},
    'IS': {'en': 'Iceland', 'de': 'Island'},
    'IN': {'en': 'India', 'de': 'Indien'},
    'ID': {'en': 'Indonesia', 'de': 'Indonesien'},
    'IR': {'en': 'Iran', 'de': 'Iran'},
    'IQ': {'en': 'Iraq', 'de': 'Irak'},
    'IE': {'en': 'Ireland', 'de': 'Irland'},
    'IL': {'en': 'Israel', 'de': 'Israel'},
    'IT': {'en': 'Italy', 'de': 'Italien'},
    'JM': {'en': 'Jamaica', 'de': 'Jamaika'},
    'JP': {'en': 'Japan', 'de': 'Japan'},
    'JO': {'en': 'Jordan', 'de': 'Jordanien'},
    'KZ': {'en': 'Kazakhstan', 'de': 'Kasachstan'},
    'KE': {'en': 'Kenya', 'de': 'Kenia'},
    'KI': {'en': 'Kiribati', 'de': 'Kiribati'},
    'KP': {'en': 'North Korea', 'de': 'Nordkorea'},
    'KR': {'en': 'South Korea', 'de': 'Südkorea'},
    'KW': {'en': 'Kuwait', 'de': 'Kuwait'},
    'KG': {'en': 'Kyrgyzstan', 'de': 'Kirgisistan'},
    'LA': {'en': 'Laos', 'de': 'Laos'},
    'LV': {'en': 'Latvia', 'de': 'Lettland'},
    'LB': {'en': 'Lebanon', 'de': 'Libanon'},
    'LS': {'en': 'Lesotho', 'de': 'Lesotho'},
    'LR': {'en': 'Liberia', 'de': 'Liberia'},
    'LY': {'en': 'Libya', 'de': 'Libyen'},
    'LI': {'en': 'Liechtenstein', 'de': 'Liechtenstein'},
    'LT': {'en': 'Lithuania', 'de': 'Litauen'},
    'LU': {'en': 'Luxembourg', 'de': 'Luxemburg'},
    'MK': {'en': 'North Macedonia', 'de': 'Nordmazedonien'},
    'MG': {'en': 'Madagascar', 'de': 'Madagaskar'},
    'MW': {'en': 'Malawi', 'de': 'Malawi'},
    'MY': {'en': 'Malaysia', 'de': 'Malaysia'},
    'MV': {'en': 'Maldives', 'de': 'Malediven'},
    'ML': {'en': 'Mali', 'de': 'Mali'},
    'MT': {'en': 'Malta', 'de': 'Malta'},
    'MH': {'en': 'Marshall Islands', 'de': 'Marshallinseln'},
    'MR': {'en': 'Mauritania', 'de': 'Mauretanien'},
    'MU': {'en': 'Mauritius', 'de': 'Mauritius'},
    'MX': {'en': 'Mexico', 'de': 'Mexiko'},
    'FM': {'en': 'Micronesia', 'de': 'Mikronesien'},
    'MD': {'en': 'Moldova', 'de': 'Moldawien'},
    'MC': {'en': 'Monaco', 'de': 'Monaco'},
    'MN': {'en': 'Mongolia', 'de': 'Mongolei'},
    'ME': {'en': 'Montenegro', 'de': 'Montenegro'},
    'MA': {'en': 'Morocco', 'de': 'Marokko'},
    'MZ': {'en': 'Mozambique', 'de': 'Mosambik'},
    'MM': {'en': 'Myanmar', 'de': 'Myanmar'},
    'NA': {'en': 'Namibia', 'de': 'Namibia'},
    'NR': {'en': 'Nauru', 'de': 'Nauru'},
    'NP': {'en': 'Nepal', 'de': 'Nepal'},
    'NL': {'en': 'Netherlands', 'de': 'Niederlande'},
    'NZ': {'en': 'New Zealand', 'de': 'Neuseeland'},
    'NI': {'en': 'Nicaragua', 'de': 'Nicaragua'},
    'NE': {'en': 'Niger', 'de': 'Niger'},
    'NG': {'en': 'Nigeria', 'de': 'Nigeria'},
    'NO': {'en': 'Norway', 'de': 'Norwegen'},
    'OM': {'en': 'Oman', 'de': 'Oman'},
    'PK': {'en': 'Pakistan', 'de': 'Pakistan'},
    'PW': {'en': 'Palau', 'de': 'Palau'},
    'PS': {'en': 'Palestine', 'de': 'Palästina'},
    'PA': {'en': 'Panama', 'de': 'Panama'},
    'PG': {'en': 'Papua New Guinea', 'de': 'Papua-Neuguinea'},
    'PY': {'en': 'Paraguay', 'de': 'Paraguay'},
    'PE': {'en': 'Peru', 'de': 'Peru'},
    'PH': {'en': 'Philippines', 'de': 'Philippinen'},
    'PL': {'en': 'Poland', 'de': 'Polen'},
    'PT': {'en': 'Portugal', 'de': 'Portugal'},
    'QA': {'en': 'Qatar', 'de': 'Katar'},
    'RO': {'en': 'Romania', 'de': 'Rumänien'},
    'RU': {'en': 'Russia', 'de': 'Russland'},
    'RW': {'en': 'Rwanda', 'de': 'Ruanda'},
    'KN': {'en': 'Saint Kitts and Nevis', 'de': 'St. Kitts und Nevis'},
    'LC': {'en': 'Saint Lucia', 'de': 'St. Lucia'},
    'VC': {'en': 'Saint Vincent and the Grenadines', 'de': 'St. Vincent und die Grenadinen'},
    'WS': {'en': 'Samoa', 'de': 'Samoa'},
    'SM': {'en': 'San Marino', 'de': 'San Marino'},
    'ST': {'en': 'Sao Tome and Principe', 'de': 'São Tomé und Príncipe'},
    'SA': {'en': 'Saudi Arabia', 'de': 'Saudi-Arabien'},
    'SN': {'en': 'Senegal', 'de': 'Senegal'},
    'RS': {'en': 'Serbia', 'de': 'Serbien'},
    'SC': {'en': 'Seychelles', 'de': 'Seychellen'},
    'SL': {'en': 'Sierra Leone', 'de': 'Sierra Leone'},
    'SG': {'en': 'Singapore', 'de': 'Singapur'},
    'SK': {'en': 'Slovakia', 'de': 'Slowakei'},
    'SI': {'en': 'Slovenia', 'de': 'Slowenien'},
    'SB': {'en': 'Solomon Islands', 'de': 'Salomonen'},
    'SO': {'en': 'Somalia', 'de': 'Somalia'},
    'ZA': {'en': 'South Africa', 'de': 'Südafrika'},
    'SS': {'en': 'South Sudan', 'de': 'Südsudan'},
    'ES': {'en': 'Spain', 'de': 'Spanien'},
    'LK': {'en': 'Sri Lanka', 'de': 'Sri Lanka'},
    'SD': {'en': 'Sudan', 'de': 'Sudan'},
    'SR': {'en': 'Suriname', 'de': 'Suriname'},
    'SE': {'en': 'Sweden', 'de': 'Schweden'},
    'CH': {'en': 'Switzerland', 'de': 'Schweiz'},
    'SY': {'en': 'Syria', 'de': 'Syrien'},
    'TW': {'en': 'Taiwan', 'de': 'Taiwan'},
    'TJ': {'en': 'Tajikistan', 'de': 'Tadschikistan'},
    'TZ': {'en': 'Tanzania', 'de': 'Tansania'},
    'TH': {'en': 'Thailand', 'de': 'Thailand'},
    'TL': {'en': 'Timor-Leste', 'de': 'Osttimor'},
    'TG': {'en': 'Togo', 'de': 'Togo'},
    'TO': {'en': 'Tonga', 'de': 'Tonga'},
    'TT': {'en': 'Trinidad and Tobago', 'de': 'Trinidad und Tobago'},
    'TN': {'en': 'Tunisia', 'de': 'Tunesien'},
    'TR': {'en': 'Turkey', 'de': 'Türkei'},
    'TM': {'en': 'Turkmenistan', 'de': 'Turkmenistan'},
    'TV': {'en': 'Tuvalu', 'de': 'Tuvalu'},
    'UG': {'en': 'Uganda', 'de': 'Uganda'},
    'UA': {'en': 'Ukraine', 'de': 'Ukraine'},
    'AE': {'en': 'United Arab Emirates', 'de': 'Vereinigte Arabische Emirate'},
    'GB': {'en': 'United Kingdom', 'de': 'Vereinigtes Königreich'},
    'US': {'en': 'United States', 'de': 'Vereinigte Staaten'},
    'UY': {'en': 'Uruguay', 'de': 'Uruguay'},
    'UZ': {'en': 'Uzbekistan', 'de': 'Usbekistan'},
    'VU': {'en': 'Vanuatu', 'de': 'Vanuatu'},
    'VA': {'en': 'Vatican City', 'de': 'Vatikanstadt'},
    'VE': {'en': 'Venezuela', 'de': 'Venezuela'},
    'VN': {'en': 'Vietnam', 'de': 'Vietnam'},
    'YE': {'en': 'Yemen', 'de': 'Jemen'},
    'ZM': {'en': 'Zambia', 'de': 'Sambia'},
    'ZW': {'en': 'Zimbabwe', 'de': 'Simbabwe'}
} 